---
title: "ESM206-assignment4"
author: "Claire Madden, Bridget Gibbons, Andrew Paterson"
date: "11/12/2018"
output: word_document
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE}

library(tidyverse)
library(vcdExtra)
library(RColorBrewer)
library(dplyr)
library(car)
library(effsize)
library(kableExtra)
library(ggrepel)

```

```{r, echo=FALSE, message=FALSE}

lobster_size <- read_csv("lobster_size_abundance.csv")
lobster_traps <- read_csv("lobster_traps.csv")

```


```{r, echo=FALSE}

lobster_size2 <- as.data.frame(lobster_size)
lobster_size_tidy <- expand.dft(lobster_size2, freq = "COUNT")

#If you guys don't want to change the site name here, no problem!
size_tidy <- lobster_size_tidy %>% 
  mutate(Site=
    case_when(
      SITE == "NAPL" ~ "Naples Reef",
      SITE == "AQUE" ~ "Arroyo Quemado",
      SITE == "MOHK" ~ "Mohawk Reef",
      SITE == "IVEE" ~ "Isla Vista",
      SITE == "CARP" ~ "Carpinteria"
    )
  ) %>% 
  select(-SITE)

traps_tidy <- lobster_traps %>% 
    mutate(Site=
    case_when(
      SITE == "NAPL" ~ "Naples Reef",
      SITE == "AQUE" ~ "Arroyo Quemado",
      SITE == "MOHK" ~ "Mohawk Reef",
      SITE == "IVEE" ~ "Isla Vista",
      SITE == "CARP" ~ "Carpinteria"
    )
  ) %>% 
  select(-SITE)


```

#Part 1 (Claire)
```{r, echo=FALSE}

abundance_summary <- lobster_size %>%
  group_by(SITE, YEAR) %>% 
  summarize(
    count = sum(COUNT))


traps_simple <- lobster_traps %>% 
  filter(SITE == "AQUE" | SITE == "NAPL" | SITE == "MOHK" | SITE == "IVEE" | SITE == "CARP")

traps_summary <- traps_simple %>% 
  group_by(SITE, YEAR) %>% 
  summarize(
    traps = sum(TRAPS))


```

```{r, echo=FALSE}
# my attempt at joining the data before graphing and or getting both graphs for one location on the same plane

abundance_traps <- full_join(abundance_summary, traps_summary)


both_scatter <- ggplot(abundance_traps, aes(x = YEAR))+
  geom_line(aes(y=count, color = "count"))+
  geom_line(aes(y=traps, color = "traps"))+
  facet_wrap(~SITE)+
  theme_light()+
  scale_x_continuous(expand = c(0,0))+
  labs( x = "Year",
        y = "Count")
  

both_scatter




```
```{r}

traps_scatter <- ggplot(abundance_traps, aes(x = YEAR, y = traps))+
  geom_point(aes(color = SITE))+
  geom_line(aes(color = SITE))+
  theme_classic()+
  labs(x = "Year", y= "Traps")
traps_scatter

count_scatter <- ggplot(abundance_traps, aes(x = YEAR, y = count))+
  geom_point(aes(color = SITE))+
  geom_line(aes(color = SITE))+
  theme_classic()+
  labs(x = "Year", y = "Lobsters Counted")

count_scatter


```


#Part 2 (Andrew)

```{r, echo=FALSE, include= FALSE}

#Filter for just 2017 results for Part 2, and Exploratory Histogram and QQ Plots

size_2017 <- size_tidy %>% 
  filter(YEAR == "2017") %>%
  select(SIZE, Site)

carapace_hist <- ggplot(size_2017, aes(x = SIZE))+
  geom_histogram(bins = 23, aes(fill = Site))+
  facet_wrap(~Site)

carapace_hist

carapace_qq <- ggplot(size_2017, aes(sample = SIZE))+
  geom_qq()+
  facet_wrap(~Site)

carapace_qq

#The data looks roughly normally distributed, and all sites have a sample size of greater than 30. 

```

```{r echo=FALSE, message=FALSE, include=FALSE}

#Levene's Test for Equal Variances, since we have more than two groups
#H0: Variances are equal
#HA: Variances are not equal

carapace_levene <- leveneTest(SIZE ~ Site, data = size_2017)
carapace_levene

#We reject the null hypothesis of equal variances (p < .001) based on Levene's Test.  However, we can examine the variances of each site to see if the largest is less than four times the smallest variance.  

carapace_variances <- size_2017 %>% 
  group_by(Site) %>% 
  summarize(
    Variance = var(SIZE)
  )

carapace_variances

#The largest variance is well less than four times the smallest variance, so we can assume accept the null hypothesis of equal variances and run an ANOVA.

#H0: Mean carapace sizes are equal at all sites
#HA: Mean carapace sizes vary for lobsters from at least two sites.

carapace_aov <- aov(SIZE ~ Site, data = size_2017)
summary(carapace_aov)

#boxplot for ANOVA in case we want to include this
lobster_anova <- ggplot(size_2017, aes(x = Site, y = SIZE))+
  geom_boxplot()+
  scale_x_discrete()+
  scale_y_discrete()+
  ylab("Size")+
  xlab("Site")

lobster_anova

#Making a summary table and column graph for lobster sizes

size_summary <- size_2017 %>% 
  group_by(Site) %>%
  summarize(
    'Median' = round(median(SIZE), 2),
    'Maximum' = round(max(SIZE), 2),
    'Mean' = round(mean(SIZE), 2),
    'Standard_Deviation' = round(sd(SIZE), 2),
    'Sample_Size' = length(SIZE)
  )

size_2017_col <- ggplot(size_summary, aes(x = Site, y = Mean))+
  geom_col(fill = "indianred2")+
  geom_errorbar(aes(ymin=Mean-Standard_Deviation, ymax=Mean+Standard_Deviation), size = .3, width = .2)+
  theme_classic()+
  labs(x = "Site", y = "Carapace Size")+
  scale_y_continuous(breaks=seq(0,100, by = 20), expand = c(0,0), limits = c(0,100))
                
size_2017_col

#With p = .0085, we reject the null, and assume mean carapace length varies between lobsters from at least two sites. At least two populations were taken from populations with different means.

#Post-hoc testing using Tukey's HSD

carapace_ph <- TukeyHSD(carapace_aov)
carapace_ph

#Lobster sizes differed significantly only between Naples Reef and Carpenteria, and Naples Reef and Isla Vista. 

#Cohen's d in case we want to include it

naples_2017 <- size_2017 %>% 
  filter(Site == "Naples Reef")

carp_2017 <- size_2017 %>% 
  filter(Site == "Carpinteria")

iv_2017 <- size_2017 %>% 
  filter(Site == "Isla Vista")

nap_carp_effsize <- cohen.d(naples_2017$SIZE, carp_2017$SIZE)
nap_carp_effsize

nap_iv_effsize <- cohen.d(naples_2017$SIZE, iv_2017$SIZE)
nap_iv_effsize

#Small effect size between both locations

```

**Figure 1: Mean Lobster Carapace Length at Five LTER Sites in the Santa Barbara Channel in 2017** 

```{r, echo=FALSE, message=FALSE, include=FALSE}

#Comparing the lobster sizes across the sites, and putting this information in a table.

size_summary <- size_2017 %>% 
  group_by(Site) %>% 
  summarize("Mean Size" = round(mean(SIZE), 2),
            "Sample Size" = length(Site))

size_summary

size_final <- kable(size_summary, col.names = c("Site", "Mean Carapace Size (mm)", "Sample Size"), align = "c") %>% 
  kable_styling(bootstrap_options = c("striped"))
  
size_final
```

```{r, echo=FALSE}

size_summary

size_final

```


#Part 3 (Bridget)

#The following chunks are comparing 2012 and 2017 for each site individually 

```{r, echo=FALSE}
#MPA Sites data frames

mpa_size_2012 <- lobster_size_tidy %>% 
  filter(SITE == "IVEE" | SITE == "NAPL", YEAR == "2012") %>% 
  select(YEAR, SITE, SIZE)

mpa_size_2017 <- lobster_size_tidy %>% 
  filter(SITE == "IVEE" | SITE == "NAPL", YEAR == "2017") %>% 
  select(YEAR, SITE, SIZE)

```

```{r, echo=FALSE, include=FALSE}
#MPA Sites exploratory histograms and qq plots

mpa_2012_hist <- ggplot(mpa_size_2012, aes(x = SIZE)) + 
  geom_histogram(bins = 8) +
  facet_wrap(~ SITE)

mpa_2012_hist

mpa_2012_qq <- ggplot(mpa_size_2012, aes(sample = SIZE)) +
  geom_qq() +
  facet_wrap(~ SITE)

mpa_2012_qq

mpa_2017_hist <- ggplot(mpa_size_2017, aes(x = SIZE)) + 
  geom_histogram(bins = 8) +
  facet_wrap(~ SITE)

mpa_2017_hist

mpa_2017_qq <- ggplot(mpa_size_2017, aes(sample = SIZE)) +
  geom_qq() +
  facet_wrap(~ SITE)

mpa_2017_qq
```

```{r, echo=FALSE}
#NonMPA sites data frames

nonmpa_size_2012 <- lobster_size_tidy %>% 
  filter(SITE == "AQUE" | SITE == "MOHK" | SITE == "CARP", YEAR == "2012") %>% 
  select(YEAR, SITE, SIZE)

nonmpa_size_2017 <- lobster_size_tidy %>% 
  filter(SITE == "AQUE" | SITE == "MOHK" | SITE == "CARP", YEAR == "2017") %>% 
  select(YEAR, SITE, SIZE)
```

```{r, echo=FALSE, include=FALSE}
#NonMPA Sites exploratory histograms and qq plots

nonmpa_2012_hist <- ggplot(nonmpa_size_2012, aes(x = SIZE)) + 
  geom_histogram(bins = 8) +
  facet_wrap(~ SITE)

nonmpa_2012_hist

nonmpa_2012_qq <- ggplot(nonmpa_size_2012, aes(sample = SIZE)) +
  geom_qq() +
  facet_wrap(~ SITE)

nonmpa_2012_qq

nonmpa_2017_hist <- ggplot(nonmpa_size_2017, aes(x = SIZE)) + 
  geom_histogram(bins = 8) +
  facet_wrap(~ SITE)

nonmpa_2017_hist

nonmpa_2017_qq <- ggplot(nonmpa_size_2017, aes(sample = SIZE)) +
  geom_qq() +
  facet_wrap(~ SITE)

nonmpa_2017_qq
```

```{r, echo=FALSE, include=FALSE}
#Site 1: Arroyo Quemado - nonMPA
#Make vectors for the 2012 and 2017 values
 
aq_2012 <- nonmpa_size_2012 %>% 
 filter(SITE == "AQUE") %>% 
 pull(SIZE)
 
aq_2017 <- nonmpa_size_2017 %>% 
 filter(SITE == "AQUE") %>% 
 pull(SIZE)
 
#Run an F-test for equal variance
#H0: ratio of variances = 1
#HA: ratio of variances NOT = 1
 
aq_ftest <- var.test(aq_2012, aq_2017)
aq_ftest
 
#Retain null, variances are equal. Run student's t-test
 
aq_ttest <- t.test(aq_2012, aq_2017, var.equal = TRUE)
aq_ttest
 
#p-valye of 0.2097, no significant difference in lobster sizes
 
#calculate effect size
 
aq_effsize <- cohen.d(aq_2012, aq_2017)
aq_effsize

#effect size is small (-0.256)

#Run a MWU test - 2012 data doesn't look totally normal

# H0: There is not a signficant difference in ranks for 2012 and 2017
# HA: There is a significant difference in ranks

aq_mwu <- wilcox.test(aq_2012, aq_2017)
aq_mwu

#Retain the null, there is not a significant difference in ranks. p = 0.1618
```


```{r, echo=FALSE, include=FALSE}
#Site 2: Carpinteria - nonMPA
#Make vectors for the 2012 and 2017 values
 
carp_2012 <- nonmpa_size_2012 %>% 
 filter(SITE == "CARP") %>% 
 pull(SIZE)
 
carp_2017 <- nonmpa_size_2017 %>% 
 filter(SITE == "CARP") %>% 
 pull(SIZE)

#Run an F-test for equal variance
#H0: ratio of variances = 1
#HA: ratio of variances NOT = 1
 
carp_ftest <- var.test(carp_2012, carp_2017)
carp_ftest
 
#Retain null, variances are equal. Run student's t-test
 
carp_ttest <- t.test(carp_2012, carp_2017, var.equal = TRUE)
carp_ttest
 
#p-valye of 0.1819, no significant difference in lobster sizes
 
#calculate effect size
 
carp_effsize <- cohen.d(carp_2012, carp_2017)
carp_effsize
 
#effect size is negligible (-0.159)
```


```{r, echo=FALSE, include=FALSE}
#Site 3: Mohawk Reef - nonMPA

#Make vectors for the 2012 and 2017 values

mohk_2012 <- nonmpa_size_2012 %>% 
 filter(SITE == "MOHK") %>% 
 pull(SIZE)
 
mohk_2017 <- nonmpa_size_2017 %>% 
 filter(SITE == "MOHK") %>% 
 pull(SIZE)

#Run an F-test for equal variance
#H0: ratio of variances = 1
#HA: ratio of variances NOT = 1
 
mohk_ftest <- var.test(mohk_2012, mohk_2017)
mohk_ftest
 
#Retain null, variances are equal. Run student's t-test
 
mohk_ttest <- t.test(mohk_2012, mohk_2017, var.equal = TRUE)
mohk_ttest
 
#p-valye < 0.001, significant difference in lobster sizes
 
#calculate effect size
 
mohk_effsize <- cohen.d(mohk_2012, mohk_2017)
mohk_effsize
 
#effect size is medium (0.54)
```


```{r, echo=FALSE, include=FALSE}

#Site 4: Isla Vista - MPA

#Make vectors for the 2012 and 2017 values

iv_2012 <- mpa_size_2012 %>% 
  filter(SITE == "IVEE") %>% 
  pull(SIZE)

iv_2017 <- mpa_size_2017 %>% 
  filter(SITE == "IVEE") %>% 
  pull(SIZE)

#Run an F-test for equal variance
#H0: ratio of variances = 1
#HA: ratio of variances NOT = 1

iv_ftest <- var.test(iv_2012, iv_2017)
iv_ftest

#Retain null, variances are equal. Run student's t-test

iv_ttest <- t.test(iv_2012, iv_2017, var.equal = TRUE)
iv_ttest

#p-valye of 0.0599, no significant difference in lobster sizes

#calculate effect size

iv_effsize <- cohen.d(iv_2012, iv_2017)
iv_effsize

#effect size is small (-0.377)

#Run a MWU test - 2012 data doesn't look totally normal

# H0: There is not a signficant difference in ranks for 2012 and 2017
# HA: There is a significant difference in ranks

iv_mwu <- wilcox.test(iv_2012, iv_2017)
iv_mwu

#Reject the null, there is a significant difference in ranks. p = 0.008488
```


```{r, echo=FALSE, include=FALSE}

#Site 5: Naples Reef - MPA

#Make vectors for the 2012 and 2017 values

napl_2012 <- mpa_size_2012 %>% 
  filter(SITE == "NAPL") %>% 
  pull(SIZE)

napl_2017 <- mpa_size_2017 %>% 
  filter(SITE == "NAPL") %>% 
  pull(SIZE)

#Run an F-test for equal variance
#H0: ratio of variances = 1
#HA: ratio of variances NOT = 1

napl_ftest <- var.test(napl_2012, napl_2017)
napl_ftest

#Retain null, variances are equal. Run student's t-test

napl_ttest <- t.test(napl_2012, napl_2017, var.equal = TRUE)
napl_ttest

#p-valye of 0.5002, no significant difference in lobster sizes

#calculate effect size

napl_effsize <- cohen.d(napl_2012, napl_2017)
napl_effsize

#effect size is small (-0.283)
```


```{r, echo=FALSE, include=FALSE}

#Make boxplots for MPA sites

#Isla Vista

iv_box <- lobster_size_tidy %>% 
  filter(SITE == "IVEE", YEAR == "2012" | YEAR == "2017") %>% 
  select(YEAR, SIZE) %>% 
  mutate(YEAR = factor(YEAR)) %>% 
  group_by(YEAR)

iv_boxplot <- ggplot(iv_box, aes(x = YEAR, y = SIZE)) +
  geom_boxplot()

iv_boxplot

#Naples

napl_box <- lobster_size_tidy %>% 
  filter(SITE == "NAPL", YEAR == "2012" | YEAR == "2017") %>% 
  select(YEAR, SIZE) %>% 
  mutate(YEAR = factor(YEAR)) %>% 
  group_by(YEAR)

napl_boxplot <- ggplot(napl_box, aes(x = YEAR, y = SIZE)) +
  geom_boxplot()+
  theme_classic()

napl_boxplot

```


```{r, echo=FALSE}
#Make boxplots for Non-MPA sites

#Arroyo Quemado

aq_box <- lobster_size_tidy %>% 
  filter(SITE == "AQUE", YEAR == "2012" | YEAR == "2017") %>% 
  select(YEAR, SIZE) %>% 
  mutate(YEAR = factor(YEAR)) %>% 
  group_by(YEAR)

aq_boxplot <- ggplot(aq_box, aes(x = YEAR, y = SIZE)) +
  geom_boxplot()

aq_boxplot

#Carpinteria

carp_box <- lobster_size_tidy %>% 
  filter(SITE == "CARP", YEAR == "2012" | YEAR == "2017") %>% 
  select(YEAR, SIZE) %>% 
  mutate(YEAR = factor(YEAR)) %>% 
  group_by(YEAR)

carp_boxplot <- ggplot(carp_box, aes(x = YEAR, y = SIZE)) +
  geom_boxplot()

carp_boxplot

#Mohawk Reef

mohk_box <- lobster_size_tidy %>% 
  filter(SITE == "MOHK", YEAR == "2012" | YEAR == "2017") %>% 
  select(YEAR, SIZE) %>% 
  mutate(YEAR = factor(YEAR)) %>% 
  group_by(YEAR)

mohk_boxplot <- ggplot(mohk_box, aes(x = YEAR, y = SIZE)) +
  geom_boxplot()

mohk_boxplot
```


#Part 4

```{r, echo=FALSE, message=FALSE}
#Make table with counts of legal and illegal lobsters for each site

legal_sizes <- lobster_size_tidy %>% 
  filter(SITE == "IVEE" | SITE == "NAPL" | SITE == "MOHK" | SITE == "AQUE" | SITE == "CARP") %>% 
  filter(YEAR == 2017) %>% 
  filter(SIZE != "-99999") %>% 
  select(YEAR, SITE, SIZE) %>% 
  mutate(legality = ifelse(SIZE > 83, "legal", "illegal")) %>% 
  count(SITE, legality) %>% 
  spread(legality, n) %>% 
  select(-SITE)

rownames(legal_sizes) <- c("AQUE", "CARP", "IVEE", "MOHK", "NAPL")
  
```

```{r, echo=FALSE, include=FALSE}
#Make table with proportions

legal_prop <- prop.table(as.matrix(legal_sizes), 1)

legal_prop
```

```{r, echo=FALSE, include=FALSE}
#Run chi square test on the legalilty table (original data, not prop table)

legal_x2 <- chisq.test(legal_sizes) 
legal_x2

#There is a significant association between site location and the amount of legal/illegal lobsters

```

